name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle') }}
      - name: Install Gradle
        run: gradle install
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/todo-java .
      - name: Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USER}}/todo-java:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Install Gradle
        run: gradle install
      - name: Run tests
        run: gradle test